### ISSUE TITLE
Layout of Lock Warning

### ISSUE THREAD

**Issue by hellwegdigital** [gabrielmaldi/chrome-lock-tab#3]
Thank you for the app.

Would it be possible to change the lock alert layout? Maybe with a custom text and colored with an exclamation mark?

**Comment by gabrielmaldi** [comment]
Thanks for the suggestion, @hellwegdigital!

I'd love to be able to present a custom dialog or at least change the text; unfortunately, Lock Tab uses the `beforeunload` browser event:

https://github.com/gabrielmaldi/chrome-lock-tab/blob/4c7ee39bb705ca4eaca0b5276c7f814b77672de7/src/script.js#L37-L49

Browsers are very restrictive in what they allow you to do in that handler, you can't even [set a custom text](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#compatibility_notes) like it used to be possible (this is to [avoid a security concern](https://groups.google.com/a/chromium.org/g/blink-dev/c/YIH8CoYVGSg/m/Di7TsljXDQAJ) — as you can see in the code, Lock Tab sets the text anyway in case this behavior is reversed in the future, but I wouldn't count on it at all).

A custom Lock Tab dialog is also out of the question because we have no way of knowing when the tab is about to be closed (besides `beforeunload` which is not designed to alter the page in any way).

So sadly I think we have no room to change anything regarding this.

Thanks anyway for your contribution!
